// Generated by gir (https://github.com/gtk-rs/gir @ 5433e2582f83)
// from C:\Users\dan\Documents\code\libnice\build\nice (@ ac4bb22ebbfc)
// from C:\vcpkg\installed\x64-windows\share\gir-1.0 (@ 65be7019941e)
// DO NOT EDIT

use crate::{ffi,CandidateType};
#[cfg(feature = "v0_1_19")]
#[cfg_attr(docsrs, doc(cfg(feature = "v0_1_19")))]
use crate::{Address,CandidateTransport};
use glib::{translate::*};

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct Candidate(Boxed<ffi::NiceCandidate>);

    match fn {
        copy => |ptr| ffi::nice_candidate_copy(ptr),
        free => |ptr| ffi::nice_candidate_free(ptr),
        type_ => || ffi::nice_candidate_get_type(),
    }
}

impl Candidate {
    #[doc(alias = "nice_candidate_new")]
    pub fn new(type_: CandidateType) -> Candidate {
        unsafe {
            from_glib_full(ffi::nice_candidate_new(type_.into_glib()))
        }
    }

    #[cfg(feature = "v0_1_15")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v0_1_15")))]
    #[doc(alias = "nice_candidate_equal_target")]
    pub fn equal_target(&self, candidate2: &Candidate) -> bool {
        unsafe {
            from_glib(ffi::nice_candidate_equal_target(self.to_glib_none().0, candidate2.to_glib_none().0))
        }
    }

    #[cfg(feature = "v0_1_19")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v0_1_19")))]
    #[doc(alias = "nice_candidate_relay_address")]
    pub fn relay_address(&self, addr: &mut Address) {
        unsafe {
            ffi::nice_candidate_relay_address(self.to_glib_none().0, addr.to_glib_none_mut().0);
        }
    }

    #[cfg(feature = "v0_1_20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v0_1_20")))]
    #[doc(alias = "nice_candidate_stun_server_address")]
    pub fn stun_server_address(&self, addr: &mut Address) -> bool {
        unsafe {
            from_glib(ffi::nice_candidate_stun_server_address(self.to_glib_none().0, addr.to_glib_none_mut().0))
        }
    }

    #[cfg(feature = "v0_1_19")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v0_1_19")))]
    #[doc(alias = "nice_candidate_transport_to_string")]
    pub fn transport_to_string(transport: CandidateTransport) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::nice_candidate_transport_to_string(transport.into_glib()))
        }
    }

    #[cfg(feature = "v0_1_19")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v0_1_19")))]
    #[doc(alias = "nice_candidate_type_to_string")]
    pub fn type_to_string(type_: CandidateType) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::nice_candidate_type_to_string(type_.into_glib()))
        }
    }
}
