[options]
library = "Nice"
version = "0.1"
min_cfg_version = "0.1"
work_mode = "sys"
target_path = "."
external_libraries = []

girs_directories = [
  "C:/Users/dan/Documents/code/libnice/build/nice",
  "C:/vcpkg/installed/x64-windows/share/gir-1.0"
]